# Generated by Django 4.0.4 on 2022-05-20 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import skills.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', skills.models.TitleField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', skills.models.TitleField(max_length=50, unique=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserTagValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.tagvalue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagvalues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tagvalue',
            name='user',
            field=models.ManyToManyField(related_name='values', through='skills.UserTagValue', to=settings.AUTH_USER_MODEL),
        ),
    ]
